Refactor/custom properties
MI-FraunhoferIWM/data2rdf pull request #74
Opened 2024-12-19 09:36 UTC by MBueschelberger

2024-12-24 16:13 UTC, yoavnash requested changes
This is a comment for the SDK, but I’d like to mention it here as well: I think a better name for `sectionize_metadata` would be `CustomPropertiesSchema` (I imagine camel case fits better here than snake case).

2024-12-24 16:13 UTC, yoavnash commented on data2rdf/pipelines/main.py
>      def plain_metadata(cls) -> Dict[str, Any]:
Note that `cls` is being used here, as well as in other places, whereas `self` would be the correct term.

2025-01-17 14:28 UTC, MBueschelberger commented on data2rdf/parsers/base.py
> +    def to_dict(
I think both would be comforable. But rather in the next release...

2025-01-17 14:31 UTC, MBueschelberger commented on data2rdf/parsers/base.py
> +    def to_dict(
I made the following issue:
https://github.com/MI-FraunhoferIWM/data2rdf/issues/76

2025-01-17 14:32 UTC, MBueschelberger commented
> This is a comment for the SDK, but I’d like to mention it here as well: I think a better name for `sectionize_metadata` would be `CustomPropertiesSchema` (I imagine camel case fits better here than snake case).

why camel case? It is a method and hence the convention is snake case.

2025-01-17 14:39 UTC, MBueschelberger commented on data2rdf/parsers/base.py
>          return self._time_series
`dataframe` would be the correct corresponding term.

`data` is missleading because you can also run the pipeline without a `dataframe` and hence only end up with `metadata`, which is not included in the `dataframe`.

`tensor` would imply that the overall content of the `dataframe` would be numeric, which is not always the case. The term does not fix semantically.

`array` might be more suitable, but it is not explicit in its dimensionality. It can be 2D, 3D, 4D etc...

A `dataframe` is generally a 2-D dimensional structure, can hold any dtatype and relates to how we are generally treating the data to be parsed.

2025-01-17 15:28 UTC, MBueschelberger commented on data2rdf/models/graph.py
> +    )
I would avoid any direct package dependency since it will cause problems in the future...

As an alternative, we can remove the schema here and make sure through the `sectionize_metadata` callabl in the sdk, that the measurement unit is in the correct schema as it is needed, when the `to_dict` method is called in data2rdf.

2025-01-17 15:31 UTC, MBueschelberger commented on data2rdf/qudt/utils.py
> +) -> Optional[str]:
Has been adapted.

2025-01-17 15:33 UTC, MBueschelberger commented on data2rdf/qudt/utils.py
> +        {"label": str(row["label"]), "symbol": str(row["symbol"])}
The iri is a required argument for this function. Hence I do not see any benefit providing it as an output.

2025-01-17 15:52 UTC, MBueschelberger commented on data2rdf/pipelines/main.py
>      def plain_metadata(cls) -> Dict[str, Any]:
This has been adapted now for the overall package.

2025-01-17 15:53 UTC, MBueschelberger commented on data2rdf/parsers/base.py
>          return self._time_series
`datafame` has now been applied in the overall package. A deprication warning has been added to `time_series` and `time_series_metadata`.

2025-01-17 16:08 UTC, yoavnash commented
> > This is a comment for the SDK, but I’d like to mention it here as well: I think a better name for `sectionize_metadata` would be `CustomPropertiesSchema` (I imagine camel case fits better here than snake case).
> 
> why camel case? It is a method and hence the convention is snake case.

I'm not sure why I didn't use snake case, but the point still holds.

2025-01-17 16:09 UTC, yoavnash commented on data2rdf/models/graph.py
> +    )
Do you mean `custom_propertiesschema`? (see https://github.com/MI-FraunhoferIWM/data2rdf/pull/74#issuecomment-2598690950)
I guess we can live with this duplication, so need for the extra work for now.

2025-01-17 16:11 UTC, MBueschelberger commented
> > > This is a comment for the SDK, but I’d like to mention it here as well: I think a better name for `sectionize_metadata` would be `CustomPropertiesSchema` (I imagine camel case fits better here than snake case).
> > 
> > 
> > why camel case? It is a method and hence the convention is snake case.
> 
> I'm not sure why I didn't use snake case, but the point still holds.

sure, the name makes sense and I would rename it in the SDK. Just was wondering about the case schema.

2025-01-17 16:12 UTC, MBueschelberger commented on data2rdf/models/graph.py
> +    )
Okay. As a workaround, the `custom_properties_schema`  still can wrap around the correct schema needed by the SDK in case of any incomptibility.

2025-01-17 16:13 UTC, MBueschelberger commented
> > > > This is a comment for the SDK, but I’d like to mention it here as well: I think a better name for `sectionize_metadata` would be `CustomPropertiesSchema` (I imagine camel case fits better here than snake case).
> > > 
> > > 
> > > why camel case? It is a method and hence the convention is snake case.
> > 
> > 
> > I'm not sure why I didn't use snake case, but the point still holds.
> 
> sure, the name makes sense and I would rename it in the SDK. Just was wondering about the case schema.

Maybe `make_custom_properties_schema` would be even better, because it's a function?

2025-01-17 16:14 UTC, yoavnash approved these changes

2025-01-20 09:58 UTC, merged